spring:
  profiles:
    active: dev
    include:
      - aws
      - credentials
  config:
    import:

---

spring:
  profiles:
    group:
      "jonghyun": "jonghyundb, common"
      "dev": "devdb,common"

---

spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fever-final.cy76xlw8fwhe.ap-northeast-2.rds.amazonaws.com:3306/fever?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: fever
    password: fever2022

---

spring:
  config:
    activate:
      on-profile: "jonghyundb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fever-final.cy76xlw8fwhe.ap-northeast-2.rds.amazonaws.com:3306/fever?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: fever
    password: fever2022

---

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5e3755636ff2c2835946338bd7552ee3 # 카카오 디벨로퍼 REST API 키   클라이언트 ID
            redirect-uri: http://localhost:8081/test/signin #"{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            provider:
              kakao:
                authorization_uri: https://kauth.kakao.com/oauth/authorize
                token_uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user_name_attribute: id
  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            revision_field_name: rev_id
            store_data_at_delete: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  header: Authorization
  secret: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKaWhvQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNjM3OTQ5ODUwLCJleHAiOjE2Mzc5NTM0NTB9.9cxwL02Dy3IWhIXPULbY49Pe4vdlgnOqXpHnBeRNeuQ
  token-validity-in-seconds: 86400

---
  logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error